// auto-generated by lnp-tbox.sage.
// 
// protocol is statistically complete with correctness error >= 1 - 2^(-3)
// protocol is simulatable under MLWE(29,35,[-1,1])
// protocol is knowledge-sound with knowledge error <= 2^(-127.0) under MSIS(23,220,2^(41.236603))
// 
// Ring
// degree d = 64
// modulus q = 70368744177829, log(q) ~ 46.0
// factors q = q1
// 
// Compression
// D = 17
// gamma = 56869422, log(gamma) ~ 25.76115
// 
// Dimensions of secrets
// s1: m1 = 151
// m: l = 0
// s2: m2 = 69
// 
// Size of secrets
// l2(s1) <= alpha = 5346.0
// m unbounded
// s2 uniform in [-nu,nu] = [-1,1]
// 
// Norm proofs
// binary: yes (dimension: 109)
// exact euclidean: no
// approximate infinity: yes (psi: 2928.3203, dimension: 96, bound: 84.2700000000000)
// 
// Challenge space
// c uniform in [-omega,omega] = [-8,8], o(c)=c, sqrt(l1(o(c)*c)) <= eta = 140
// 
// Standard deviations
// stdev1 = 13002342.4, log(stdev1/1.55) = 23.0
// stdev2 = 6348.8, log(stdev2/1.55) = 12.0
// stdev3 = 6348.8, log(stdev3/1.55) = 12.0
// stdev4 = 50790.4, log(stdev4/1.55) = 15.0
// stdev5 = 13002342.4, log(stdev4/1.55) = 23.0
// 
// Repetition rate
// M1 = 2.1628382
// M2 = 2.926106
// M3 = 1.0295918
// M4 = 1.0227652
// M5 = 1.4748786
// total = 9.8290462
// 
// Security
// MSIS dimension: 23
// MSIS root hermite factor: 1.0043612
// MLWE dimension: 29
// MLWE root hermite factor: 1.004382
// 
// Proof size
// ~ 50.5136718750000 KiB
// 
// 50 bit moduli for degree 64: [1125899906840833, 1125899906839937, 1125899906837633]
// bit length of products: [49, 99, 149]
// inverses: [1, -162099428551732, 296975494591860]

#include "lazer.h"
static const limb_t _paramsTP_q_limbs[] = {70368744177829UL};
static const int_t _paramsTP_q = {{(limb_t *)_paramsTP_q_limbs, 1, 0}};
static const limb_t _paramsTP_qminus1_limbs[] = {70368744177828UL};
static const int_t _paramsTP_qminus1 = {{(limb_t *)_paramsTP_qminus1_limbs, 1, 0}};
static const limb_t _paramsTP_m_limbs[] = {1237374UL};
static const int_t _paramsTP_m = {{(limb_t *)_paramsTP_m_limbs, 1, 0}};
static const limb_t _paramsTP_mby2_limbs[] = {618687UL};
static const int_t _paramsTP_mby2 = {{(limb_t *)_paramsTP_mby2_limbs, 1, 0}};
static const limb_t _paramsTP_gamma_limbs[] = {56869422UL};
static const int_t _paramsTP_gamma = {{(limb_t *)_paramsTP_gamma_limbs, 1, 0}};
static const limb_t _paramsTP_gammaby2_limbs[] = {28434711UL};
static const int_t _paramsTP_gammaby2 = {{(limb_t *)_paramsTP_gammaby2_limbs, 1, 0}};
static const limb_t _paramsTP_pow2D_limbs[] = {131072UL};
static const int_t _paramsTP_pow2D = {{(limb_t *)_paramsTP_pow2D_limbs, 1, 0}};
static const limb_t _paramsTP_pow2Dby2_limbs[] = {65536UL};
static const int_t _paramsTP_pow2Dby2 = {{(limb_t *)_paramsTP_pow2Dby2_limbs, 1, 0}};
static const limb_t _paramsTP_Bsq_limbs[] = {2083856487569353233UL, 0UL};
static const int_t _paramsTP_Bsq = {{(limb_t *)_paramsTP_Bsq_limbs, 2, 0}};
static const limb_t _paramsTP_scM1_limbs[] = {7451547249687409637UL, 3003835360069575919UL, 2UL};
static const int_t _paramsTP_scM1 = {{(limb_t *)_paramsTP_scM1_limbs, 3, 0}};
static const limb_t _paramsTP_scM2_limbs[] = {9578942225184763211UL, 17083641274772167011UL, 2UL};
static const int_t _paramsTP_scM2 = {{(limb_t *)_paramsTP_scM2_limbs, 3, 0}};
static const limb_t _paramsTP_scM3_limbs[] = {10209454655680014627UL, 545871887530908525UL, 1UL};
static const int_t _paramsTP_scM3 = {{(limb_t *)_paramsTP_scM3_limbs, 3, 0}};
static const limb_t _paramsTP_scM4_limbs[] = {14449991392749102949UL, 419943645420513404UL, 1UL};
static const int_t _paramsTP_scM4 = {{(limb_t *)_paramsTP_scM4_limbs, 3, 0}};
static const limb_t _paramsTP_scM5_limbs[] = {12878261797966324650UL, 8759963938991843146UL, 1UL};
static const int_t _paramsTP_scM5 = {{(limb_t *)_paramsTP_scM5_limbs, 3, 0}};
static const limb_t _paramsTP_stdev1sq_limbs[] = {169060907886838UL, 0UL};
static const int_t _paramsTP_stdev1sq = {{(limb_t *)_paramsTP_stdev1sq_limbs, 2, 0}};
static const limb_t _paramsTP_stdev2sq_limbs[] = {40307261UL, 0UL};
static const int_t _paramsTP_stdev2sq = {{(limb_t *)_paramsTP_stdev2sq_limbs, 2, 0}};
static const limb_t _paramsTP_stdev3sq_limbs[] = {40307261UL, 0UL};
static const int_t _paramsTP_stdev3sq = {{(limb_t *)_paramsTP_stdev3sq_limbs, 2, 0}};
static const limb_t _paramsTP_stdev4sq_limbs[] = {2579664732UL, 0UL};
static const int_t _paramsTP_stdev4sq = {{(limb_t *)_paramsTP_stdev4sq_limbs, 2, 0}};
static const limb_t _paramsTP_stdev5sq_limbs[] = {169060907886838UL, 0UL};
static const int_t _paramsTP_stdev5sq = {{(limb_t *)_paramsTP_stdev5sq_limbs, 2, 0}};
static const limb_t _paramsTP_inv2_limbs[] = {35184372088914UL};
static const int_t _paramsTP_inv2 = {{(limb_t *)_paramsTP_inv2_limbs, 1, 1}};
static const limb_t _paramsTP_inv4_limbs[] = {17592186044457UL};
static const int_t _paramsTP_inv4 = {{(limb_t *)_paramsTP_inv4_limbs, 1, 1}};
static const unsigned int _paramsTP_n[0] = {};
static const limb_t _paramsTP_Bz3sqr_limbs[] = {27753065054UL, 0UL};
static const int_t _paramsTP_Bz3sqr = {{(limb_t *)_paramsTP_Bz3sqr_limbs, 2, 0}};
static const limb_t _paramsTP_Bz4_limbs[] = {1776196163486UL, 0UL};
static const int_t _paramsTP_Bz4 = {{(limb_t *)_paramsTP_Bz4_limbs, 2, 0}};
static const limb_t _paramsTP_Bz5_limbs[] = {116404791770224342UL, 0UL};
static const int_t _paramsTP_Bz5 = {{(limb_t *)_paramsTP_Bz5_limbs, 2, 0}};
static const limb_t _paramsTP_Pmodq_limbs[] = {180121643247UL};
static const int_t _paramsTP_Pmodq = {{(limb_t *)_paramsTP_Pmodq_limbs, 1, 1}};
static const limb_t _paramsTP_Ppmodq_0_limbs[] = {40650337UL};
static const int_t _paramsTP_Ppmodq_0 = {{(limb_t *)_paramsTP_Ppmodq_0_limbs, 1, 0}};
static const limb_t _paramsTP_Ppmodq_1_limbs[] = {33812961UL};
static const int_t _paramsTP_Ppmodq_1 = {{(limb_t *)_paramsTP_Ppmodq_1_limbs, 1, 0}};
static const limb_t _paramsTP_Ppmodq_2_limbs[] = {23603937UL};
static const int_t _paramsTP_Ppmodq_2 = {{(limb_t *)_paramsTP_Ppmodq_2_limbs, 1, 0}};
static const int_srcptr _paramsTP_l2Bsq[] = {};
static const int_srcptr _paramsTP_Ppmodq[] = {_paramsTP_Ppmodq_0, _paramsTP_Ppmodq_1, _paramsTP_Ppmodq_2};
static const polyring_t _paramsTP_ring = {{_paramsTP_q, 64, 47, 6, moduli_d64, 3, _paramsTP_Pmodq, _paramsTP_Ppmodq, _paramsTP_inv2}};
static const dcompress_params_t _paramsTP_dcomp = {{ _paramsTP_q, _paramsTP_qminus1, _paramsTP_m, _paramsTP_mby2, _paramsTP_gamma, _paramsTP_gammaby2, _paramsTP_pow2D, _paramsTP_pow2Dby2, 17, 0, 21 }};
static const abdlop_params_t _paramsTP_tbox = {{ _paramsTP_ring, _paramsTP_dcomp, 151, 69, 0, 17, 23, _paramsTP_Bsq, 1, 8, 5, 140, 1, 23, _paramsTP_scM1, _paramsTP_stdev1sq, 2, 12, _paramsTP_scM2, _paramsTP_stdev2sq}};
static const abdlop_params_t _paramsTP_quad_eval_ = {{ _paramsTP_ring, _paramsTP_dcomp, 151, 69, 14, 3, 23, _paramsTP_Bsq, 1, 8, 5, 140, 1, 23, _paramsTP_scM1, _paramsTP_stdev1sq, 2, 12, _paramsTP_scM2, _paramsTP_stdev2sq}};
static const abdlop_params_t _paramsTP_quad_many_ = {{ _paramsTP_ring, _paramsTP_dcomp, 151, 69, 16, 1, 23, _paramsTP_Bsq, 1, 8, 5, 140, 1, 23, _paramsTP_scM1, _paramsTP_stdev1sq, 2, 12, _paramsTP_scM2, _paramsTP_stdev2sq}};
static const lnp_quad_eval_params_t _paramsTP_quad_eval = {{ _paramsTP_quad_eval_, _paramsTP_quad_many_, 4}};
static const lnp_tbox_params_t _paramsTP = {{ _paramsTP_tbox, _paramsTP_quad_eval, 109, _paramsTP_n, 96, 0, 109, 2, 12, _paramsTP_scM3, _paramsTP_stdev3sq, 2, 15, _paramsTP_scM4, _paramsTP_stdev4sq, _paramsTP_Bz3sqr, _paramsTP_Bz4, &_paramsTP_l2Bsq[0], _paramsTP_inv4, 51726UL }};
static const add_lnp_tbox_params_t add_tbox_para = {{26, 26, 7, 40, 1, 2, 16, 68, 32, 26, 100, 103, 143, -261993004995, 59, 150, 32, 2, 23, _paramsTP_scM5, _paramsTP_stdev5sq,  _paramsTP_Bz5 }};

static const unsigned int paramsTP_Ps[109] = {42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150};

static const limb_t paramsTP_p_limbs[] = {1774UL};
static const int_t paramsTP_p = {{(limb_t *)paramsTP_p_limbs, 1, 0}};
static const limb_t paramsTP_pinv_limbs[] = {1388334862584UL};
static const int_t paramsTP_pinv = {{(limb_t *)paramsTP_pinv_limbs, 1, 0}};
static const unsigned int paramsTP_s1_indices[151] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150};
static const lin_params_t paramsTP = {
{ _paramsTP, 64, paramsTP_p, paramsTP_pinv, 1, 
paramsTP_s1_indices, 151,
NULL, 0, 
paramsTP_Ps, 109, 
NULL, NULL, 
NULL, NULL }
};

